# Generated by Django 6.1 on 2026-08-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва товару')),
                ('color', models.CharField(blank=True, max_length=100, null=True, verbose_name='Колір')),
                ('storage', models.CharField(blank=True, max_length=100, null=True, verbose_name="Вбудована пам'ять")),
                ('product_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Код товару')),
                ('reviews', models.IntegerField(blank=True, null=True, verbose_name='Кількість рецензій')),
                ('screen_diagonal', models.CharField(blank=True, max_length=100, null=True, verbose_name='Діагональ екрану')),
                ('display_resolution', models.CharField(blank=True, max_length=100, null=True, verbose_name='Роздільна здатність екрану')),
                ('photos', models.JSONField(blank=True, default=list, verbose_name='Фотографії')),
                ('characteristics', models.JSONField(blank=True, default=dict, verbose_name='Характеристики')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
            },
        ),
    ]
