# Generated by Django 6.1 on 2026-08-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0003_product_price_product_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='parser',
            field=models.CharField(choices=[('requests', 'Req'), ('selenium', 'Sel'), ('playwright', 'Pla')], default='SEL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(verbose_name='Посилання на товар'),
        ),
    ]
