# Generated by Django 6.1 on 2026-08-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0004_product_parser_alter_product_url'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('parser', 'url'), name='parser_url_unique'),
        ),
    ]
