# Generated by Django 6.1 on 2026-08-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0005_product_parser_url_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='parser',
            field=models.CharField(choices=[('requests', 'Requests'), ('selenium', 'Selenium'), ('playwright', 'Playwright')]),
        ),
    ]
